### ISSUE TITLE
Error while training NLU model

### ISSUE THREAD

**Issue by msamogh** [Revmaker/innatis#22]
I got this error while training.

Here's my training configuration:
```yaml
language: en
pipeline:
  - name: "tokenizer_whitespace"
  - name: "ner_crf"
  - name: "ner_synonyms"
  - name: "innatis.classifiers.BertIntentClassifier"
    "batch_size": 64
    "epochs": 10
    "learning_rate": 2e-6
    "max_seq_length": 128

```

And here is the stack trace:
```md
2019-05-03 16:17:32 INFO     tensorflow  - Using /tmp/tfhub_modules to cache modules.
2019-05-03 16:17:32 INFO     tensorflow  - Downloading TF-Hub Module 'https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1'.
2019-05-03 16:17:53 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 31.62MB
2019-05-03 16:18:13 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 61.62MB
2019-05-03 16:18:31 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 81.62MB
2019-05-03 16:18:51 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 111.62MB
2019-05-03 16:19:08 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 141.62MB
2019-05-03 16:19:27 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 171.62MB
2019-05-03 16:19:43 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 191.62MB
2019-05-03 16:20:02 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 211.62MB
2019-05-03 16:20:22 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 231.62MB
2019-05-03 16:20:42 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 251.62MB
2019-05-03 16:21:14 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 261.62MB
2019-05-03 16:21:31 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 281.62MB
2019-05-03 16:21:47 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 301.62MB
2019-05-03 16:22:27 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 321.62MB
2019-05-03 16:22:43 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 331.62MB
2019-05-03 16:23:12 INFO     tensorflow  - Downloading https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1: 351.62MB
2019-05-03 16:23:24 INFO     tensorflow  - Downloaded https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1, Total size: 421.86MB
2019-05-03 16:23:24 INFO     tensorflow  - Downloaded TF-Hub Module 'https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1'.
2019-05-03 16:23:25 WARNING  tensorflow  - From /home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-03 16:23:26 INFO     tensorflow  - Saver not created because there are no variables in the graph to restore
2019-05-03 16:23:27.013251: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-03 16:23:27.237821: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2208000000 Hz
2019-05-03 16:23:27.240991: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x6947670 executing computations on platform Host. Devices:
2019-05-03 16:23:27.241052: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-03 16:23:27 INFO     rasa_nlu.training_data.loading  - Training data format of data/nlu_data.md is md
2019-05-03 16:23:27 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 10 (1 distinct intents)
	- Found intents: 'query_open_positions'
	- entity examples: 9 (2 distinct entities)
	- found entities: 'role', 'pincode'

2019-05-03 16:23:27 INFO     rasa_nlu.model  - Starting to train component tokenizer_whitespace
2019-05-03 16:23:27 INFO     rasa_nlu.model  - Finished training component.
2019-05-03 16:23:27 INFO     rasa_nlu.model  - Starting to train component ner_crf
2019-05-03 16:23:27 INFO     rasa_nlu.model  - Finished training component.
2019-05-03 16:23:27 INFO     rasa_nlu.model  - Starting to train component ner_synonyms
2019-05-03 16:23:27 INFO     rasa_nlu.model  - Finished training component.
2019-05-03 16:23:27 INFO     rasa_nlu.model  - Starting to train component intent_classifier_bert
2019-05-03 16:23:27 INFO     tensorflow  - ***** Running training *****
2019-05-03 16:23:27 INFO     tensorflow  - Num examples = 10
2019-05-03 16:23:27 INFO     tensorflow  - Batch size = 64
2019-05-03 16:23:27 INFO     tensorflow  - Num steps = 1
2019-05-03 16:23:27 INFO     tensorflow  - Num epochs = 10
2019-05-03 16:23:27 INFO     tensorflow  - Using config: {'_model_dir': './tmp/bert', '_tf_random_seed': None, '_save_summary_steps': 500, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f97c39327f0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
2019-05-03 16:23:27 INFO     tensorflow  - Calling model_fn.
2019-05-03 16:23:29 INFO     tensorflow  - Saver not created because there are no variables in the graph to restore
2019-05-03 16:23:29 WARNING  tensorflow  - From /home/msamogh/rasa-workshop/lib/python3.7/site-packages/innatis-0.5.8-py3.7.egg/innatis/classifiers/bert/run_classifier.py:250: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2019-05-03 16:23:29 WARNING  tensorflow  - From /home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/training/learning_rate_decay_v2.py:321: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
2019-05-03 16:23:29 WARNING  tensorflow  - From /home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
/home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/ops/gradients_impl.py:110: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2019-05-03 16:23:34 WARNING  tensorflow  - From /home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/ops/metrics_impl.py:455: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-05-03 16:23:34 INFO     tensorflow  - Done calling model_fn.
2019-05-03 16:23:34 INFO     tensorflow  - Create CheckpointSaverHook.
2019-05-03 16:23:37 INFO     tensorflow  - Graph was finalized.
2019-05-03 16:23:40 INFO     tensorflow  - Running local_init_op.
2019-05-03 16:23:40 INFO     tensorflow  - Done running local_init_op.
2019-05-03 16:23:45 INFO     tensorflow  - Saving checkpoints for 0 into ./tmp/bert/model.ckpt.
2019-05-03 16:24:20 INFO     tensorflow  - loss = 0.0, step = 1
2019-05-03 16:24:20 INFO     tensorflow  - accuracy = 1.0, loss = 0.0
2019-05-03 16:24:20 INFO     tensorflow  - Saving checkpoints for 1 into ./tmp/bert/model.ckpt.
2019-05-03 16:24:23 INFO     tensorflow  - Loss for final step: 0.0.
2019-05-03 16:24:23 INFO     tensorflow  - Calling model_fn.
2019-05-03 16:24:26 INFO     tensorflow  - Saver not created because there are no variables in the graph to restore
2019-05-03 16:24:26 INFO     tensorflow  - Done calling model_fn.
2019-05-03 16:24:26 WARNING  tensorflow  - From /home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/saved_model/signature_def_utils_impl.py:205: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
2019-05-03 16:24:26 INFO     tensorflow  - Graph was finalized.
2019-05-03 16:24:27 WARNING  tensorflow  - From /home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-05-03 16:24:27 INFO     tensorflow  - Restoring parameters from ./tmp/bert/model.ckpt-1
2019-05-03 16:24:29 WARNING  tensorflow  - From /home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1070: get_checkpoint_mtimes (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file utilities to get mtimes.
2019-05-03 16:24:30 INFO     tensorflow  - Running local_init_op.
2019-05-03 16:24:30 INFO     tensorflow  - Done running local_init_op.
2019-05-03 16:24:30 INFO     rasa_nlu.model  - Finished training component.
2019-05-03 16:24:31 INFO     tensorflow  - Calling model_fn.
2019-05-03 16:24:33 INFO     tensorflow  - Saver not created because there are no variables in the graph to restore
2019-05-03 16:24:33 INFO     tensorflow  - Done calling model_fn.
2019-05-03 16:24:33 INFO     tensorflow  - Signatures INCLUDED in export for Classify: None
2019-05-03 16:24:33 INFO     tensorflow  - Signatures INCLUDED in export for Regress: None
2019-05-03 16:24:33 INFO     tensorflow  - Signatures INCLUDED in export for Predict: ['serving_default']
2019-05-03 16:24:33 INFO     tensorflow  - Signatures INCLUDED in export for Train: None
2019-05-03 16:24:33 INFO     tensorflow  - Signatures INCLUDED in export for Eval: None
2019-05-03 16:24:33 INFO     tensorflow  - Restoring parameters from ./tmp/bert/model.ckpt-1
2019-05-03 16:24:33 INFO     tensorflow  - Assets added to graph.
2019-05-03 16:24:34 INFO     tensorflow  - Assets written to: /home/msamogh/rasa-workshop/rasa-currency/models/current/nlu/temp-b'1556880871'/assets
2019-05-03 16:24:34 INFO     tensorflow  - SavedModel written to: /home/msamogh/rasa-workshop/rasa-currency/models/current/nlu/temp-b'1556880871'/saved_model.pb
2019-05-03 16:24:35 INFO     rasa_nlu.model  - Successfully saved model into '/home/msamogh/rasa-workshop/rasa-currency/models/current/nlu'
2019-05-03 16:24:35 INFO     __main__  - Finished training
(rasa-workshop) msamogh@msamogh-rbc:~/rasa-workshop/rasa-currency$ cd rasa-currency/^C
(rasa-workshop) msamogh@msamogh-rbc:~/rasa-workshop/rasa-currency$ subl
(failed reverse-i-search)`evaluate': source d^Cel/setup.bash 
(rasa-workshop) msamogh@msamogh-rbc:~/rasa-workshop/rasa-currency$ make run-nlu 
python -m rasa_nlu.server --path ./models
2019-05-03 16:26:42+0530 [-] Log opened.
2019-05-03 16:26:42+0530 [-] Site starting on 5000
2019-05-03 16:26:42+0530 [-] Starting factory <twisted.web.server.Site object at 0x7f9d271942b0>
2019-05-03 16:26:46+0530 [-] /home/msamogh/rasa-workshop/lib/python3.7/site-packages/h5py/__init__.py:36: builtins.FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
2019-05-03 16:26:51.140703: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-03 16:26:51.277682: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2208000000 Hz
2019-05-03 16:26:51.280416: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x7f9d0a630620 executing computations on platform Host. Devices:
2019-05-03 16:26:51.280485: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-03 16:26:51+0530 [-] 2019-05-03 16:26:51 WARNING  tensorflow  - From /home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/contrib/predictor/saved_model_predictor.py:153: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
2019-05-03 16:26:51+0530 [-] Instructions for updating:
2019-05-03 16:26:51+0530 [-] This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
2019-05-03 16:26:52+0530 [-] 2019-05-03 16:26:52 WARNING  tensorflow  - From /home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
2019-05-03 16:26:52+0530 [-] Instructions for updating:
2019-05-03 16:26:52+0530 [-] Use standard file APIs to check for files with this prefix.
2019-05-03 16:26:53+0530 [-] 2019-05-03 16:26:53 WARNING  tensorflow  - From /home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
2019-05-03 16:26:53+0530 [-] Instructions for updating:
2019-05-03 16:26:53+0530 [-] Colocations handled automatically by placer.
2019-05-03 16:26:54+0530 [-] "127.0.0.1" - - [03/May/2019:10:56:54 +0000] "GET /parse?q=&project=current&model=nlu HTTP/1.1" 200 135 "-" "curl/7.47.0"
2019-05-03 16:28:05+0530 [-] 2019-05-03 16:28:05 ERROR    __main__  - Cannot use the default session to evaluate tensor: the tensor's graph is different from the session's graph. Pass an explicit session to `eval(session=sess)`.
2019-05-03 16:28:05+0530 [-] Traceback (most recent call last):
2019-05-03 16:28:05+0530 [-]   File "/home/msamogh/rasa-workshop/lib/python3.7/site-packages/rasa_nlu-0.14.3-py3.7.egg/rasa_nlu/server.py", line 257, in parse
2019-05-03 16:28:05+0530 [-]     self.data_router.parse, data))
2019-05-03 16:28:05+0530 [-]   File "/home/msamogh/rasa-workshop/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
2019-05-03 16:28:05+0530 [-]     result = inContext.theWork()
2019-05-03 16:28:05+0530 [-]   File "/home/msamogh/rasa-workshop/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
2019-05-03 16:28:05+0530 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2019-05-03 16:28:05+0530 [-]   File "/home/msamogh/rasa-workshop/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
2019-05-03 16:28:05+0530 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2019-05-03 16:28:05+0530 [-]   File "/home/msamogh/rasa-workshop/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
2019-05-03 16:28:05+0530 [-]     return func(*args,**kw)
2019-05-03 16:28:05+0530 [-]   File "/home/msamogh/rasa-workshop/lib/python3.7/site-packages/rasa_nlu-0.14.3-py3.7.egg/rasa_nlu/data_router.py", line 272, in parse
2019-05-03 16:28:05+0530 [-]     model)
2019-05-03 16:28:05+0530 [-]   File "/home/msamogh/rasa-workshop/lib/python3.7/site-packages/rasa_nlu-0.14.3-py3.7.egg/rasa_nlu/project.py", line 270, in parse
2019-05-03 16:28:05+0530 [-]     response = self._models[model_name].parse(text, time)
2019-05-03 16:28:05+0530 [-]   File "/home/msamogh/rasa-workshop/lib/python3.7/site-packages/rasa_nlu-0.14.3-py3.7.egg/rasa_nlu/model.py", line 357, in parse
2019-05-03 16:28:05+0530 [-]     component.process(message, **self.context)
2019-05-03 16:28:05+0530 [-]   File "/home/msamogh/rasa-workshop/lib/python3.7/site-packages/innatis-0.5.8-py3.7.egg/innatis/classifiers/bert_intent_classifier.py", line 170, in process
2019-05-03 16:28:05+0530 [-]     index = tf.argmax(probabilities, axis=0).eval()
2019-05-03 16:28:05+0530 [-]   File "/home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 695, in eval
2019-05-03 16:28:05+0530 [-]     return _eval_using_default_session(self, feed_dict, self.graph, session)
2019-05-03 16:28:05+0530 [-]   File "/home/msamogh/rasa-workshop/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 5172, in _eval_using_default_session
2019-05-03 16:28:05+0530 [-]     raise ValueError("Cannot use the default session to evaluate tensor: "
2019-05-03 16:28:05+0530 [-] ValueError: Cannot use the default session to evaluate tensor: the tensor's graph is different from the session's graph. Pass an explicit session to `eval(session=sess)`.
2019-05-03 16:28:05+0530 [-] "127.0.0.1" - - [03/May/2019:10:58:04 +0000] "GET /parse?q=Are+there+any+openings+for+a+technical+role+nearby+560042&project=current&model=nlu HTTP/1.1" 500 175 "-" "curl/7.47.0"
^C2019-05-03 16:33:36+0530 [-] Received SIGINT, shutting down.
2019-05-03 16:33:36+0530 [twisted.web.server.Site] (TCP Port 5000 Closed)
2019-05-03 16:33:36+0530 [-] Stopping factory <twisted.web.server.Site object at 0x7f9d271942b0>
2019-05-03 16:33:36+0530 [-] Main loop terminated.
^CMakefile:40: recipe for target 'run-nlu' failed
make: *** [run-nlu] Interrupt
```

**Comment by samhavens** [comment]
There is an unmerged patch for this. Change bertclassifier line 170 to `index = tf.argmax(probabilities, axis=0).eval(session=tf.Session())`

I am looking into if this is the right way, that's why we haven't merged this... but it should run.

**Comment by samhavens** [comment]
#21 should be merged soon and has a fix for this @msamogh

**Comment by msamogh** [comment]
Thanks, will check it out!

**Comment by nimf** [comment]
#21 was merged, so I'm closing this.
