### ISSUE TITLE
TypeError: cache_key() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by gcgloven** [Revmaker/innatis#30]
My rasa version is 1.1.4
Python version 3.5.7

I encounter a problem with the cashe_key part, all I did was installing innitas and updated the config file.
after writing congif file as :
``` ymal
pipeline: 
  - name: "tokenizer_whitespace"
  - name: "ner_crf"
  - name: "ner_synonyms"
  - name: "innatis.classifiers.BertIntentClassifier"
    pretrained_model_dir: '/bert'
    epochs: 10
    batch_size: 64
```
``` shell
Traceback (most recent call last):
  File "/home/iim/Desktop/botdesign/myenv/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/home/iim/Desktop/botdesign/myenv/lib/python3.5/site-packages/rasa/__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/iim/Desktop/botdesign/myenv/lib/python3.5/site-packages/rasa/cli/train.py", line 84, in train
    kwargs=extract_additional_arguments(args),
  File "/home/iim/Desktop/botdesign/myenv/lib/python3.5/site-packages/rasa/train.py", line 40, in train
    kwargs=kwargs,
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/home/iim/Desktop/botdesign/myenv/lib/python3.5/site-packages/rasa/train.py", line 135, in train_async
    kwargs=kwargs,
  File "/home/iim/Desktop/botdesign/myenv/lib/python3.5/site-packages/rasa/train.py", line 188, in _do_training
    fixed_model_name=fixed_model_name,
  File "/home/iim/Desktop/botdesign/myenv/lib/python3.5/site-packages/rasa/train.py", line 382, in _train_nlu_with_validated_data
    config, nlu_data_directory, _train_path, fixed_model_name="nlu"
  File "/home/iim/Desktop/botdesign/myenv/lib/python3.5/site-packages/rasa/nlu/train.py", line 81, in train
    trainer = Trainer(nlu_config, component_builder)
  File "/home/iim/Desktop/botdesign/myenv/lib/python3.5/site-packages/rasa/nlu/model.py", line 151, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "/home/iim/Desktop/botdesign/myenv/lib/python3.5/site-packages/rasa/nlu/model.py", line 163, in _build_pipeline
    component = component_builder.create_component(component_cfg, cfg)
  File "/home/iim/Desktop/botdesign/myenv/lib/python3.5/site-packages/rasa/nlu/components.py", line 456, in create_component
    component_config, Metadata(cfg.as_dict(), None)
  File "/home/iim/Desktop/botdesign/myenv/lib/python3.5/site-packages/rasa/nlu/components.py", line 384, in __get_cached_component
    cache_key = component_class.cache_key(component_meta, model_metadata)
TypeError: cache_key() takes 2 positional arguments but 3 were given

```

**Comment by nimf** [comment]
@gcgloven I'm sorry, we haven't tested innatis with the Rasa > 0.14

**Comment by vighnesh202** [comment]
@gcgloven After installing proper version of RASA and executing the training process is not taking place, although there is no error console is idle and not moving forward. Is it is because my system doesn't have the computing power. My system RAM is 12 GB
