### ISSUE TITLE
"TypeError: cache_key() takes 2 positional arguments but 3 were given"

### ISSUE THREAD

**Issue by vighnesh202** [Revmaker/innatis#31]
After training the model with "rasa train nlu", I ended up with
Traceback (most recent call last):
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vighnesh.paramasivam\AppData\Local\Continuum\anaconda2\envs\python36\Scripts\rasa.exe\__main__.py", line 9, in <module>
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\site-packages\rasa\__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\site-packages\rasa\cli\train.py", line 136, in train_nlu
    fixed_model_name=args.fixed_model_name,
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\site-packages\rasa\train.py", line 384, in train_nlu
    _train_nlu_async(config, nlu_data, output, train_path, fixed_model_name)
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\site-packages\rasa\train.py", line 414, in _train_nlu_async
    persist_nlu_training_data=persist_nlu_training_data,
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\site-packages\rasa\train.py", line 443, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\site-packages\rasa\nlu\train.py", line 68, in train
    trainer = Trainer(nlu_config, component_builder)
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\site-packages\rasa\nlu\model.py", line 151, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\site-packages\rasa\nlu\model.py", line 163, in _build_pipeline
    component = component_builder.create_component(component_cfg, cfg)
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\site-packages\rasa\nlu\components.py", line 479, in create_component
    component_config, Metadata(cfg.as_dict(), None)
  File "c:\users\vighnesh.paramasivam\appdata\local\continuum\anaconda2\envs\python36\lib\site-packages\rasa\nlu\components.py", line 407, in __get_cached_component
    cache_key = component_class.cache_key(component_meta, model_metadata)
TypeError: cache_key() takes 2 positional arguments but 3 were given

My config.yml is,
language: en
pipeline:
  - name: "tokenizer_whitespace"
  - name: "ner_crf"
  - name: "ner_synonyms"
  - name: "innatis.classifiers.BertIntentClassifier"
    pretrained_model_dir: '/path/to/uncased_L-24_H-1024_A-16'
    epochs: 10
    batch_size: 64 

and my nlu.md is,
## intent:greet
- hey
- hello
- good morning
- good evening
- hey there

## intent:project_usecase
- need some information on [pv first](project_name)
- wanted to known about [pv first](project_name)
- what is [pv first](project_name)
- explain [pv first](project_name)
- what is the business need of [pv first](project_name)

## intent:client_info
- who are the clients of [pv first](project_name)
- which company uses [pv_first](project_name)
- where is [pv first](project_name) used
- who adopted [pv first](project_name)

## intent:person_enquiry
- who is [kalyanasundaram](person)
- do you know about [kalyanasundaram](person)

## intent:full_form
- what is the fullform of [pv_first](project_name)
- expand [pv_first](project_name)

## intent:owner
- who is the owner for [pv first](project_name)
- leader of [pv first](project_name)

**Comment by wrat** [comment]
So what is the solution for this issue?
